version: '2'
services:
  web:
    build: .
    command: npm start
    ports:
      - "3000:3000"
  
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6: