version: '2'
services:
  node-app:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/studentmgmt
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    networks:
      - node-network

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb_data:/data/db   # Mounts a local folder to store MongoDB data
    networks:
      - node-network

networks:
  node-network:
    driver: bridge